name: Build & Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          script: |
            echo "==== Pulling latest code ===="
            cd ~/covid19-vent-list || git clone https://github.com/${{ github.repository }} ~/covid19-vent-list
            cd ~/covid19-vent-list
            git fetch origin main
            git reset --hard origin/main

            echo "==== Building backend ===="
            docker build -t covid-backend:latest -f backend/Dockerfile ./backend

            echo "==== Building frontend ===="
            docker build -t covid-frontend:latest -f frontend/Dockerfile ./frontend

            echo "==== Stopping old containers ===="
            docker stop backend || true && docker rm backend || true
            docker stop frontend || true && docker rm frontend || true

            echo "==== Running backend ===="
            docker run -d --name backend --restart unless-stopped -p 5000:5000 covid-backend:latest

            echo "==== Running frontend ===="
            docker run -d --name frontend --restart unless-stopped -p 80:80 covid-frontend:latest

            echo "✅ Deployment complete."

